accounts: {}
protocols:
  - command: 012-PsiThaCa
activation:
  protocol_hash: PsiThaCaT47Zboaw71QWScM8sXeMM7bbQFncK9FLqYc6EKdpjVP
  protocol_parameters:
    preserved_cycles: 3
    blocks_per_cycle: 128
    blocks_per_commitment: 16
    blocks_per_stake_snapshot: 64
    blocks_per_voting_period: 10240
    hard_gas_limit_per_operation: '1040000'
    hard_gas_limit_per_block: '5200000'
    proof_of_work_threshold: '-1'
    tokens_per_roll: '8000000000'
    seed_nonce_revelation_tip: '125000'
    baking_reward_fixed_portion: '10000000'
    baking_reward_bonus_per_slot: '4286'
    endorsing_reward_per_slot: '2857'
    hard_storage_limit_per_operation: '60000'
    origination_size: 257
    cost_per_byte: '1000'
    quorum_max: 7000
    quorum_min: 2000
    min_proposal_quorum: 500
    liquidity_baking_subsidy: '2500000'
    liquidity_baking_sunset_level: 525600
    liquidity_baking_escape_ema_threshold: 100000
    max_operations_time_to_live: 120
    minimal_block_delay: "30"
    delay_increment_per_round: "15"
    consensus_committee_size: 7000
    consensus_threshold: 4667
    minimal_participation_ratio:
      numerator: 2
      denominator: 3
    max_slashing_period: 2
    frozen_deposits_percentage: 10
    double_baking_punishment: "640000000"
    ratio_of_frozen_deposits_slashed_per_double_endorsement:
      numerator: 1
      denominator: 2
archive_tarball_url: null
bootstrap_peers: []
expected_proof_of_work: 0
full_snapshot_url: null
images:
  octez: tezos/tezos:v12.0-rc1-release
is_invitation: false
node_config_network:
  activation_account_name: archive-baking-node-0
  chain_name: test-chain
  genesis:
    block: YOUR_GENESIS_BLOCK_HASH_HERE
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: '2022-01-18T02:25:38.452047+00:00'
nodes:
  archive-baking-node:
    instances:
    - bake_using_accounts:
      - archive-baking-node-0
      config:
        shell:
          history_mode: archive
      is_bootstrap_node: true
    runs:
    - octez_node
    - baker
    storage_size: 15Gi
  rolling-node: null
rolling_snapshot_url: null
rolling_tarball_url: null
should_generate_unsafe_deterministic_data: true
signers:
  tezos-signer-0:
    sign_for_accounts:
    - archive-baking-node-0
zerotier_config:
  zerotier_network: null
  zerotier_token: null
