accounts: {}
activation:
  protocol_hash: PtLimaPtLMwfNinJi9rCfDPWea8dFgTZ1MeJ9f1m2SRic6ayiwW
  protocol_parameters:
    baking_reward_bonus_per_slot: '4286'
    baking_reward_fixed_portion: '10000000'
    blocks_per_commitment: 4
    blocks_per_cycle: 8
    blocks_per_stake_snapshot: 4
    cache_sampler_state_cycles: 8
    cache_script_size: 100000000
    cache_stake_distribution_cycles: 8
    consensus_committee_size: 5000
    consensus_threshold: 4667
    cost_per_byte: '250'
    cycles_per_voting_period: 1
    dal_parametric:
      availability_threshold: 50
      endorsement_lag: 2
      feature_enable: true
      number_of_shards: 2048
      number_of_slots: 256
      page_size: 4096
      redundancy_factor: 16
      slot_size: 1048576
    delay_increment_per_round: '5'
    double_baking_punishment: '640000000'
    endorsing_reward_per_slot: '2857'
    frozen_deposits_percentage: 10
    hard_gas_limit_per_block: '5200000'
    hard_gas_limit_per_operation: '1040000'
    hard_storage_limit_per_operation: '60000'
    liquidity_baking_subsidy: '2500000'
    liquidity_baking_toggle_ema_threshold: 100000
    max_operations_time_to_live: 120
    max_slashing_period: 2
    min_proposal_quorum: 500
    minimal_block_delay: '5'
    minimal_participation_ratio:
      denominator: 3
      numerator: 2
    minimal_stake: '6000000000'
    nonce_revelation_threshold: 4
    origination_size: 257
    preserved_cycles: 3
    proof_of_work_threshold: '-1'
    quorum_max: 7000
    quorum_min: 2000
    ratio_of_frozen_deposits_slashed_per_double_endorsement:
      denominator: 2
      numerator: 1
    sc_rollup_challenge_window_in_blocks: 40
    sc_rollup_commitment_period_in_blocks: 20
    sc_rollup_enable: true
    sc_rollup_max_active_outbox_levels: 20160
    sc_rollup_max_lookahead_in_blocks: 30000
    sc_rollup_max_number_of_cemented_commitments: 5
    sc_rollup_max_number_of_messages_per_commitment_period: 32765
    sc_rollup_max_outbox_messages_per_level: 100
    sc_rollup_number_of_sections_in_dissection: 32
    sc_rollup_origination_size: 6314
    sc_rollup_stake_amount: '32000000'
    sc_rollup_timeout_period_in_blocks: 500
    seed_nonce_revelation_tip: '125000'
    tx_rollup_commitment_bond: '10000000000'
    tx_rollup_cost_per_byte_ema_factor: 120
    tx_rollup_enable: true
    tx_rollup_finality_period: 10
    tx_rollup_hard_size_limit_per_inbox: 500000
    tx_rollup_hard_size_limit_per_message: 5000
    tx_rollup_max_commitments_count: 30
    tx_rollup_max_inboxes_count: 15
    tx_rollup_max_messages_per_inbox: 1010
    tx_rollup_max_ticket_payload_size: 2048
    tx_rollup_max_withdrawals_per_batch: 15
    tx_rollup_origination_size: 4000
    tx_rollup_rejection_max_proof_size: 30000
    tx_rollup_sunset_level: 10000000
    tx_rollup_withdraw_period: 10
    vdf_difficulty: '100000'
    zk_rollup_enable: true
    zk_rollup_min_pending_to_process: 10
    zk_rollup_origination_size: 4000
bootstrap_peers: []
expected_proof_of_work: 0
images:
  octez: tezos/tezos:v15-release
is_invitation: false
node_config_network:
  activation_account_name: archive-baking-node-0
  chain_name: chain-1
  genesis:
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: '2023-02-21T06:55:13.938990+00:00'
node_globals:
  env:
    all:
      TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER: Y
nodes:
  archive-baking-node:
    instances:
    - bake_using_accounts:
      - archive-baking-node-0
      config:
        metrics_addr:
        - :9932
        shell:
          history_mode: archive
      is_bootstrap_node: true
    runs:
    - octez_node
    - baker
    storage_size: 15Gi
  node1:
    instances:
    - config:
        metrics_addr: :9932
        shell:
          history_mode: rolling
      is_bootstrap_node: false
    - config:
        metrics_addr: :9932
        shell:
          history_mode: rolling
      is_bootstrap_node: false
    - config:
        metrics_addr: :9932
        shell:
          history_mode: rolling
      is_bootstrap_node: false
    resources:
      limits:
        cpu: '2'
        memory: 8Gi
      requests:
        cpu: '2'
        memory: 8Gi
    storage_size: 15Gi
  rolling-node: null
protocols:
- command: PtLimaPt
  vote:
    liquidity_baking_toggle_vote: pass
should_generate_unsafe_deterministic_data: true
signers:
  tezos-signer-0:
    sign_for_accounts:
    - archive-baking-node-0
snapshot_source: null
zerotier_config:
  zerotier_network: null
  zerotier_token: null
